<Project Sdk="Microsoft.NET.Sdk.Web"><ItemGroup><ProjectReference Include="../MonolitoMod.Contracts/MonolitoMod.Contracts.csproj" /><ProjectReference Include="../MonolitoMod.EventBus/MonolitoMod.EventBus.csproj" /><ProjectReference Include="../Modules/Inventory/MonolitoMod.Inventory/MonolitoMod.Inventory.csproj" /><ProjectReference Include="../Modules/Notifications/MonolitoMod.Notifications/MonolitoMod.Notifications.csproj" /></ItemGroup></Project>
