<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AWSProjectType>Lambda</AWSProjectType><!-- Sin esto, "dotnet publish" no genera el .runtimeconfig.json para un proyecto tipo Library (default sin <OutputType>Exe</OutputType>) --><GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles></PropertyGroup><ItemGroup><ProjectReference Include="../../MonolitoMod.Contracts/MonolitoMod.Contracts.csproj" /></ItemGroup><ItemGroup><PackageReference Include="Amazon.Lambda.Core" Version="3.3.0" /><PackageReference Include="Amazon.Lambda.SQSEvents" Version="3.0.0" /><PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="3.0.0" /><PackageReference Include="AWSSDK.SecretsManager" Version="4.0.100.8" /><PackageReference Include="Npgsql" Version="10.0.3" /></ItemGroup></Project>
